### ISSUE TITLE
string constructor should not use double

### ISSUE THREAD

**Issue by schveiguy** [jaypha/fixed#6]
First, the whole reason to have a fixed-point system is to avoid the vagaries of floating point. I do not want a string to parse in a fixed representation that will be incorrect. e.g.:

```D
auto f = Fixed!2("10000000000000005.00");
writeln(f); // 10000000000000004.00
```

Second, it requires sscanf, under the hood. It does black magic. I'd rather not rely on black magic. Or libc if possible ;)

Third, parsing 2 integers instead of a double is way faster. Again parsing floating point is black magic, and really *really* hard to get right. It's why D still relies on sscanf.

I was considering using this in a project of mine. But I can't accept this limitation. I may create a PR if this might be approved. But the statement in the readme saying "Perhaps change the string -> fixed algorithm to avoid using floating point. Not sure if it is worth the effort" gives me pause.

Let me know.

**Comment by jaypha** [comment]
Hi schveiguy,
I did not consider it worth the effort because I no longer work with D, and I did not anticipate my code being used much. But I acknowledge that it is a serious flaw, and if you were to write a replacement for the string parsing that doesn't use floating point or scanf, I will paste it in.
Regards

**Comment by schveiguy** [comment]
OK, thanks. I'll work on a PR.

I think your project might be the only one of its kind in code.dlang.org. All the others I found are focused on implementing a decimal spec, whereas I just want a simple integer that has X decimal places. If you want to relinquish control of the project to someone else, I'd be happy to take it over so it can be maintained.

**Comment by m3m0ry** [comment]
@schveiguy How is the PR going?
@jaypha Are you going to abandon this project?
I would be happy to take over, since i need exactly this as well. Actually i have a version myself, which is very similar to yours.

**Comment by schveiguy** [comment]
@m3m0ry I actually have not done it yet, as I currently am using a rough substitute, and so the need is not so pressing. I do plan on getting to it, but would be happy if someone else did it too.

**Comment by m3m0ry** [comment]
Actually my FixedPoint struct is almost finished. So I will probably do my own thing.
Yes this is a horrible way to collaborate :)
But i need the experience, regarding operator overloading, casting, testing and packaging of a d project.
I can notify you if you will, once i am finished (i hope i am finished by monday, since i got most of it done already anyway).

**Comment by m3m0ry** [comment]
Alright, i got my first dub project going :)
https://github.com/m3m0ry/fixedpoint
It currently only supports addition and subtraction. I need to think about how i want to implement multiplication and division.
Also i need to implement casting from Fixed to another fixed.
Documentation and readme will be improved as well.
And my functions could use some "pure" and "nothrow".
I am happy about any feedback.

**Comment by schveiguy** [comment]
Well, I'm good moving to a maintained package. So I'm OK to let this go.
